name: Build and push Docker images
on:
  push:
    branches: [main]
    tags:
      - "*"
jobs:
  publish:
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openstates/bobsled
          dockerfile: /github/workspace/Dockerfile
          tag_with_ref: true
          tags: latest
    runs-on: ubuntu-18.04
